### ISSUE TITLE
Cache traced dependencies

### ISSUE THREAD

**Issue by ggrimbert** [amodrojs/amodro-trace#5]
Hi,

I come with a feature request : I think that you should use a cache system for previously traced dependencies.

Let me explain : Some of my files are extending another one (a base-viewmodel), this dependency is required multiple times, and have multiple dependencies. My problem is that at each time this dependency is found, the entire dependency tree is reloaded, so my build takes many time. 
For information, I have about 300 files...

Is there an existing way to prevent this, or do you need to implement some kind of caching ?

**Comment by jrburke** [comment]
I can see where this would be helpful. We should outline it a bit more, here is a pass, but open to other ideas:

A new option for the options argument passed to amodro-trace in the first position. Maybe call it `entries`.

`entries` should be in the same structure as the `traced` array options and should include at least the `id` and `dependents` properties.

`entries` objects would not be subject to the read or write transforms, and would just be returned in the output as they were passed in, not subject to things like `fileContents` options on the current trace call.

I am not sure if that will all work out internally, but trying to get a feel for how it might operate.

**Comment by ggrimbert** [comment]
So `entries` would not be traced ? In my case every dependency should be traced, but only once.

Maybe the solution is an internal array `tracedDependencies`, that lists every file already traced.
So when a dependency is found, before doing everything with it, check the `tracedDependencies` to see if it has already been done, if not, it traces the dependency, and then add it into `tracedDependencies`.

**Comment by jrburke** [comment]
Since the goal of an amodro.trace() call is to be a functional call, not retain state across calls, then further calls to trace() would need to know about previous trace results. So the idea around `entries` was to give trace() the results of a previous trace to use for that next trace() call.

Maybe it would be clearer if the parameter was called `traced` instead of `entries` would make that clearer, to match the `traced` property name that is returned in the `traceResult`.

Or maybe I am misunderstanding the request: is the concern about a retracing that is done inside one call to amodro.trace()?

**Comment by EisenbergEffect** [comment]
@jrburke I think that would work. We're using amodro.trace extensively inside the Aurelia CLI (it's pretty cool...you should check it out some time). Right now, my original implementation is pretty primitive and naive. There are probably a lot of improvements that could be made. We're investigating to see if we can get some easy wins around performance. Since we have to call the tracing logic multiple times, we think there's a lot of duplicate work or retracing going on that isn't necessary. We would love to have some way to not do work that has already been done. If that means creating an object to pass to the trace function, that should be fine for us.

**Comment by jrburke** [comment]
The [issue5-trace-cache branch](https://github.com/amodrojs/amodro-trace/compare/issue5-trace-cache) experiments with a `traced` option. It is fairly basic, uses the `traced` array items for their `id` and `deps` properties to short circuit file IO and AST parsing for those items in the `traced` array.

I published it to the amodro-trace@beta tag in npm. Try it via `npm install amodro-trace@beta`. The version number should be `0.4.0-beta`. 

I would appreciate some feedback on that version to know if:
- the results are correct.
- it helps noticeably with the stacked trace runs.

**Comment by EisenbergEffect** [comment]
Thanks @jrburke!
@ggrimbert Want to try it out in the cli and let us know how it goes?

**Comment by ggrimbert** [comment]
I tried but I should have missed something.  With my current configuration I see no changes.

Can you show me how to use this option ?

**Comment by ggrimbert** [comment]
I tried your code in debug mode.

In file trace.js : line 170, the context.depsForId list is wrong; I think this comes from aurelia-cli. 
@EisenbergEffect At this point, every dependency defined with a main takes the "name" of : name + main
For example in aurelia.json I have : 

```
 {
            "name": "aurelia-templating-router",
            "path": "../node_modules/aurelia-templating-router/dist/amd",
            "main": "aurelia-templating-router"
          },
```

The dependencies in context.depsForId will become : aurelia-templating-router/aurelia-templating-router, so deps is never filled with a lot of dependencies. But my file is looking for aurelia-templating-router, so it's never found in context.depsForId.

@jrburke Could this cause any problem in your code  ?

In addition, even if a dependency has been found, the complete way of tracing is done again.
I see the onOk method running for every dependency, even if this has been already traced before. And the entire dependency tree is done again. I guess that I should check myself the traced dependencies and not send them to amodro ?

**Comment by jrburke** [comment]
The `traced` support right now is pretty basic, just focused on avoiding further file IO and AST parsing of a file. It will still trace the dependencies for anything in `traced`, but just short circuit the file IO/AST parts.

Also, it regenerates the `deps` and `dependents` fields, does not reuse those from the `traced` option. I can see `dependents` being different, as further `trace()` calls expose more modules that depend on that module. However, I am surprised that `deps` would be different (`context.depsForId` is used to generate `deps`).

Given that and you found some IDs have changed, that implies to me that the loader config between two `trace()` calls are different. This would be a problem: if a loader config is different, with things like different paths/packages config, that could result in different IDs. It will be hard to reuse previous `trace()` runs for a `traced` cache support if the IDs for the same module are different. The IDs really need to stay consistent.

So it sounds like these things need to get sorted:

1)  Is the cli code using different loader config (paths/packages/map config) for different `trace()`? Can this be avoided? I think this may explain ID mismatches.

2) For amodro-trace: perhaps merge the `dependents` from `traced` with any new ones found in the current `trace()` run, so that the final data from the last `trace()` call has the data from all the previous runs.

3) For amodro-trace: consider deeper optimization to avoid even the lighter tracing that is done for `traced`. This one is a bit more difficult because the amodro-trace code assumes that all `dependents` are known at the time the module is considered done, defined. This would take a bit more thought.

**Comment by ggrimbert** [comment]
I'll try to explain what i've understood... @EisenbergEffect Could you tell me if i'm wrong ?

So, there is one loader config, and it is the same passed to trace() for each call.
The list of files to trace is known by aurelia cli and a call to trace() is made for each one. 
Each file has its own dependencies (of course), but some dependencies could have been already read.

When It comes inside trace() for my files (not dependencies in node_modules), the `paths` list contains about 20~30 files, and `inlinedIds` about 300 (it contains everything) and both arrays contain content previously traced.

For example, here are the contents for one file : 

`paths` : 
![image](https://cloud.githubusercontent.com/assets/15869188/19317025/ed7b0ffc-90a3-11e6-8603-993c7c9d5943.png)

`inlinedIds` for filePath N°24 : 
![image](https://cloud.githubusercontent.com/assets/15869188/19317098/303afd0c-90a4-11e6-8348-45d419f67778.png)

`inlinedIds` contains, I guess, the dependencies for each path. In addition, some dependencies are bundle of other projects. 

So without talking about ID mismatches, I do believe that merging all trace results and checking it before doing anything could be a solution.

**Comment by EisenbergEffect** [comment]
They would definitely need to be merged after each call. That's probably the missing piece.

**Comment by jrburke** [comment]
Thinking more about this one:

> 2) For amodro-trace: perhaps merge the dependents from traced with any new ones found in the current trace() run, so that the final data from the last trace() call has the data from all the previous runs.

This may not be what is desirable if trace() is focused on a functional approach: for the current trace, only dependents in that trace should be in the `dependents` section.

I am also having trouble following the issue now, feel like maybe we are not all on the same page on what we are thinking this feature should do.

What would really help me follow is a small test case that documents an "expected" output even if that does not happen now, so I can see how amodro-trace might need to change to get to an expected output. I could also adapt that test case to be run as part of the unit tests to ensure it continues to work in the future.

As far as pace of resolution, I usually just have the weekends now to look at this sort of thing.

**Comment by ggrimbert** [comment]
I created two projects to try reproducing the problem.

`requiredProject` contains a base-viewmodel with some dependencies. (https://github.com/ggrimbert/requiredProject.git)
`requiringProject` contains two files that requires base-viewmodel from `requiredProject` (https://github.com/ggrimbert/requiringProject.git)

To test it, you just have to launch from `requiringProject`'s root `au build`.

**Comment by jrburke** [comment]
I tried out the sample projects, but since I don't know aurelia, it was hard for me to know what to look at. Something simpler that showed just calling the amodro function a couple of times and describing the expected output would help me to more quickly understand what is desired.

**Comment by 3cp** [comment]
@jrburke I tried your branch
* the results are correct. --> Yes
* it helps noticeably with the stacked trace runs. --> Not really

Basically, the slowest part of aurelia-cli is writeTransform, not repeated parsing. So I tried to cache contents, which solved aurelia-cli performance issue.

More details updated here: https://github.com/aurelia/cli/issues/303

aurelia-cli has embedded amodro code, you can view my change in https://github.com/huochunpeng/cli/commit/9bd5ada2510f62a98bf4678e868de2cb25da631d

On top of your change, for amodro part, I only touched `lib/build/amodro-trace/index.js` (it's `trace.js` in amodro-trace repo) to accept cached contents.

**Comment by jrburke** [comment]
@huochunpeng thanks for looking into this! I added reuse of the `item.contents` in [this commit](https://github.com/amodrojs/amodro-trace/commit/32dc5cd49f758d95433cad4ea8931bd2f9069939) in the [issue5-trace-cache branch](https://github.com/amodrojs/amodro-trace/compare/issue5-trace-cache).

If that change looks good to you, and if I hear back from the aurelia folks that this overall change is good to go, then I will push it to master and tag/release it. Some notes to myself:

- [ ] Update README to mention trace cache rules, including read/write transforms not used on trace cache's .contents.

**Comment by EisenbergEffect** [comment]
@huochunpeng knows better than us at this point :)

**Comment by 3cp** [comment]
@jrburke I updated my aurelia-cli patch with your change. It's all good at least for my app, thanks for the update.

@Astoker will test my PR https://github.com/aurelia/cli/pull/419 on more production aurelia apps. You might want to watch the thread.

**Comment by 3cp** [comment]
sugguest to delete one or two contents in `test/source/trace/trace-cache-1/already-traced.json`, in order for test to cover both branches of newly added `if else`.

**Comment by 3cp** [comment]
found a bug #6 in master branch.

**Comment by 3cp** [comment]
@jrburke one thing to highlight for using the new cache feature.

We found out when using stubModules, we have to skip stubbed module in the cache that we give back to amodro-trace.
More precisely, the requirejs "text" module, amodro-trace needs original "text" module to load additional text resources. Feed a stubbed "text" module back to amodro just breaks everything.

You might want to highlight this in future documentation.

**Comment by AStoker** [comment]
@jrburke, so we got our tracing issue resolved, and it looks like it just needed an additional check (https://github.com/aurelia/cli/pull/509/files/59ffcfa56c4e0c15fd3c84af54869fcf77c52262#diff-a98cd86a736a989ffcce0c1416db2d54). What are your thoughts? Does that sound correct?

**Comment by jrburke** [comment]
@AStoker I added https://github.com/amodrojs/amodro-trace/commit/2eb5765ed7e93df990a22a71f49d8bb32b64c01d to the branch for this issue, but I would like to construct a test that validates it is working correctly.

Is this to fix the [issue with stubModules for a loader plugin causing an error](https://github.com/amodrojs/amodro-trace/issues/5#issuecomment-264617314)? If so, sounds like if I do a trace with a loader plugin, then do another trace trying to use the cache from the first one, that should test out that commit change.

**Comment by 3cp** [comment]
@jrburke yes, it supposes to fix the stubModules issue.

**Comment by AStoker** [comment]
That sounds about right @jrburke. @JeroenVinke and @huochunpeng, can you think of any other test cases that would test out this fix?

**Comment by JeroenVinke** [comment]
> If so, sounds like if I do a trace with a loader plugin, then do another trace trying to use the cache from the first one, that should test out that commit change.

Exactly

**Comment by jrburke** [comment]
OK, I'm working out some open source rules at work, so I'm currently in a holding pattern before I do more work here. I hope to have it sorted in a couple weeks. In the meantime though, you could use the [issue5-trace-cache branch](https://github.com/amodrojs/amodro-trace/tree/issue5-trace-cache) in here as an npm target if you wanted to pull the latest for this issue. I just want to get the work stuff cleared up, add a test, then I'll merge that branch with master.

**Comment by jrburke** [comment]
version 1.0.0 released with the change merged, mentioned above.
